apiVersion: v1
kind: Service
metadata:
  name: web3-sample-app
  labels:
    app.kubernetes.io/name: web3-sample-app
    app.kubernetes.io/component: web
spec:
  type: LoadBalancer
  selector:
    app: web3-sample-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
