name: Cleanup old container images

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: cleanup-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Delete old untagged container images
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
        run: make cleanup-images
