name: Cleanup old container images

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: cleanup-${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Delete old untagged container images
        env:
          GH_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
        run: make cleanup-images
